#!/usr/bin/env sh

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $(basename "$0") [year] <day-number>" >&2
    exit 1
fi

if [ $# -eq 1 ]; then
    year="$(date +%Y)"
    day="$1"
else
    year="$1"
    day="$2"
fi
name="$(printf "aoc_%02d" "$day")"
project_path="$year/$name"

# Navigate to repository root
cd "$(dirname "$0")/../.."
mkdir -p "$year"
cargo new --bin "$project_path"

# Remove the [dependencies] from the Cargo.toml
sed -i '' -e '$d' -e '$d' "$project_path/Cargo.toml"

# Set the default Cargo.toml content
cat >>"$project_path/Cargo.toml" <<EOF
[[bench]]
name = "bench"
harness = false

[dependencies]
aoc-common = { path = "../../common/rust" }
anyhow = "^1.0.94"
code-timing-macros = { version = "^0.0.5", features = ["release"] }

[dev-dependencies]
criterion = "^0.5.1"
EOF

# Create the default lib.rs file
touch "$project_path/src/lib.rs"
cat >"$project_path/src/lib.rs" <<EOF
use anyhow::Result;
use aoc_common::*;

pub mod solutions {
    use super::*;

    pub fn part1(input: &str) -> Result<usize> {
        Ok(1)
    }

    pub fn part2(input: &str) -> Result<usize> {
        Ok(2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_STR: &str = "";
}
EOF

# Create a directory for the input data and create the initial file
mkdir "$project_path/input"
touch "$project_path/input/input.txt"

# Create a directory for the benchmarks and create the default content
mkdir "$project_path/benches"
touch "$project_path/benches/bench.rs"
cat >"$project_path/benches/bench.rs" <<EOF
use $name::solutions;
use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn criterion_benchmark(c: &mut Criterion) {
    let input = include_str!("../input/input.txt");

    c.bench_function("solutions::part1", |b| {
        b.iter(|| solutions::part1(black_box(input)))
    });

    c.bench_function("solutions::part2", |b| {
        b.iter(|| solutions::part2(black_box(input)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
EOF

# Create a directory for the unit tests, and it's default content
mkdir "$project_path/tests"
touch "$project_path/tests/tests.rs"
cat >"$project_path/tests/tests.rs" <<EOF
use $name::solutions;

const TEST_STR: &str = "";

#[test]
fn test_part1() {
    let result = solutions::part1(TEST_STR);
    assert_eq!(result.unwrap(), 1);
}

#[test]
fn test_part2() {
    let result = solutions::part2(TEST_STR);
    assert_eq!(result.unwrap(), 2);
}
EOF

# Create the default main.rs file
cat >"$project_path/src/main.rs" <<EOF
use anyhow::Result;
use $name::solutions;
use code_timing_macros::time_snippet;
use std::fs;

fn main() -> Result<()> {
    let input = fs::read_to_string("input/input.txt")?;

    let part1_result = time_snippet!(solutions::part1(&input)?);
    println!("Part 1 Result: {:.2}", part1_result);

    println!("---");

    let part2_result = time_snippet!(solutions::part2(&input)?);
    println!("Part 2 Result: {:.2}", part2_result);

    Ok(())
}
EOF
