#!/usr/bin/env sh

if [ $# != 1 ]; then
    echo "Usage: $(basename "$0") <day-number>" >&2
    exit 1
fi

name="$(printf "aoc_%02d" "$1")"

cargo new --bin "$name"

touch "$name/src/lib.rs"
mkdir "$name/input"
touch "$name/input/input.txt"
mkdir "$name/benches"
mkdir "$name/tests"
touch "$name/tests/tests.rs"
